### ISSUE TITLE
Create Component for Author Score

### ISSUE THREAD

**Issue by Phildesro123** [Phildesro123/Reliant#33]
![image.png](https://images.zenhubusercontent.com/5c5a203ef82e87206eca9a08/f4ed0ec7-778e-4d79-b0d4-8fc404472aec)

We need to create a component for the background info and author score, similar to the one seen in the prototype.

- [x] Create new component that will activate when we click on extension Icon

**Comment by coopermeitz** [comment]
I'll work on this over the weekend to at the very least get a sense of the syntax and React

**Comment by coopermeitz** [comment]
I added what I have to a new branch. It's pretty basic, just a pop-up with a button enabling it on a new tab. My next steps were going to be to figure out how to get it on any webpage. And I just used the .css file that came with the package but I think it can be edited so it shows up in the top right corner as we designed. The database data can be fed through the props (right now I have one for name and desc but an object could be created to encapsulate both)
