### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by yasaad** [Phildesro123/Reliant#4]

**Comment by Phildesro123** [comment]
After tonight, I'm going to try to get the proper logistics down on how to properly record things on ZenHub.

Every one needs to install node
[Node](https://nodejs.org/en/)

Fortunately for us, we found a boilerplate for this project that will get us up to speed faster than up to speed
[Boilerplate](https://github.com/kryptokinght/react-extension-boilerplate)

**Comment by TheGrim159** [comment]
Get the LTS version of Node
